import 'package:minipro/src/product/productModel.dart';
import 'package:minipro/src/page/Home/homePage.dart';

class Product {
  final List<ModelProduct> modelHouse = [
    ModelProduct(
      image: 'assets/house.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "บ้าน 1",
      productTitle: "รายละเอียดบ้าน",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
    ModelProduct(
      image: 'assets/house.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "บ้าน 1",
      productTitle: "รายละเอียดบ้าน",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
    ModelProduct(
      image: 'assets/house.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "บ้าน 1",
      productTitle: "รายละเอียดบ้าน",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
    ModelProduct(
      image: 'assets/house.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "บ้าน 1",
      productTitle: "รายละเอียดบ้าน",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
  ];
  final List<ModelProduct> modelCondo = [
    ModelProduct(
      image: 'assets/condo.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "คอนโด 1",
      productTitle: "รายละเอียดคอนโด",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
    ModelProduct(
      image: 'assets/condo.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "คอนโด 1",
      productTitle: "รายละเอียดคอนโด",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
  ];
  final List<ModelProduct> modelApartment = [
    ModelProduct(
      image: 'assets/apartment.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "อพาร์ทเม้นท์ 1",
      productTitle: "รายละเอียดอพาร์ทเม้นท์",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
    ModelProduct(
      image: 'assets/apartment.jpg',
      selectedPropertyType: 'บ้าน 1',
      selectedPriceRange: '1000000',
      selectedAreaRange: 40,
      selectedRoomRange: 3,
      selectedBathRoomRange: 2,
      selectedLocationRange: "กทม.",
      selectedFloorRange: 1,
      isChecked: 1,
      productName: "อพาร์ทเม้นท์ 1",
      productTitle: "รายละเอียดอพาร์ทเม้นท์",
      latitude: 10.2923,
      longitude: 13.553232,
    ),
  ];
}
